### ISSUE TITLE
Pressing Capslock rapidly blocks keyboard access

### ISSUE THREAD

**Issue by e-senturk** [black-dragon74/ROG-HID#5]
When I press Capslock three times repeatedly I can't access keyboard for 3-5 secons. That issue also happening randomly if I type quickly.

**Comment by black-dragon74** [comment]
I cannot reproduce this issue on my test machines. 3-5 seconds can never be the case. Considering you are somehow able to press 3 times in the span of one clock cycle of the CPU (practically impossible), the max lag you could notice is of `80 * 3 = 240` milliseconds. If you take the average, `80ms` is the lag that is actually induced in order for the system to properly handle the keypress event and set the LED.

What I did to reproduce? Kept spamming random keys on my keyboard while toggling caps lock key. The behaviour was exactly like it is supposed to be; normal.

My take on this is, Dexts run in the user space rather than running in kernel space, so, a high system load can lead to delayed interrupts sometimes, which, has nothing to do with this driver.

**Comment by e-senturk** [comment]
It happens every time I try it doesn't happen without dext. May be it doesn't happen in your system because caps lock led is working on you. But every time I try to press 3 times capslock I can't type its not happening randomly. That is not a big issue for me but when I typing something quickly it happens exactly the same way. And its definitely longer than 240ms.

**Comment by black-dragon74** [comment]
Please see https://github.com/black-dragon74/ROG-HID/issues/4#issuecomment-670781447

**Comment by e-senturk** [comment]
This issue also fixed with v1.3 thanks
